# flake8: noqa

"""
    PoE対応 WebAPI 超音波センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 2.0.x
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from myapi.api_client import ApiClient

# import Configuration
from myapi.configuration import Configuration

# import exceptions
from myapi.exceptions import OpenApiException
from myapi.exceptions import ApiAttributeError
from myapi.exceptions import ApiTypeError
from myapi.exceptions import ApiValueError
from myapi.exceptions import ApiKeyError
from myapi.exceptions import ApiException
