# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ErrorError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None):  # noqa: E501
        """ErrorError - a model defined in OpenAPI

        :param code: The code of this ErrorError.  # noqa: E501
        :type code: int
        :param message: The message of this ErrorError.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'code': int,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }

        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error_error of this ErrorError.  # noqa: E501
        :rtype: ErrorError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this ErrorError.

        HTTPステータスコード   # noqa: E501

        :return: The code of this ErrorError.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ErrorError.

        HTTPステータスコード   # noqa: E501

        :param code: The code of this ErrorError.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self):
        """Gets the message of this ErrorError.

        エラー内容   # noqa: E501

        :return: The message of this ErrorError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorError.

        エラー内容   # noqa: E501

        :param message: The message of this ErrorError.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
