# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Noise(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time_sec=None, time_weight='slow'):  # noqa: E501
        """Noise - a model defined in OpenAPI

        :param time_sec: The time_sec of this Noise.  # noqa: E501
        :type time_sec: float
        :param time_weight: The time_weight of this Noise.  # noqa: E501
        :type time_weight: str
        """
        self.openapi_types = {
            'time_sec': float,
            'time_weight': str
        }

        self.attribute_map = {
            'time_sec': 'timeSec',
            'time_weight': 'timeWeight'
        }

        self._time_sec = time_sec
        self._time_weight = time_weight

    @classmethod
    def from_dict(cls, dikt) -> 'Noise':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The noise of this Noise.  # noqa: E501
        :rtype: Noise
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_sec(self):
        """Gets the time_sec of this Noise.

        測定時間 (単位：sec)     # noqa: E501

        :return: The time_sec of this Noise.
        :rtype: float
        """
        return self._time_sec

    @time_sec.setter
    def time_sec(self, time_sec):
        """Sets the time_sec of this Noise.

        測定時間 (単位：sec)     # noqa: E501

        :param time_sec: The time_sec of this Noise.
        :type time_sec: float
        """
        if time_sec is not None and time_sec < 0:  # noqa: E501
            raise ValueError("Invalid value for `time_sec`, must be a value greater than or equal to `0`")  # noqa: E501

        self._time_sec = time_sec

    @property
    def time_weight(self):
        """Gets the time_weight of this Noise.

        時間重み付け特性   省略時：Slow   - \"slow\"：時定数1sec。   - \"fast\"：時定数0.125sec。   - \"impulse\"：時定数0.035sec。   # noqa: E501

        :return: The time_weight of this Noise.
        :rtype: str
        """
        return self._time_weight

    @time_weight.setter
    def time_weight(self, time_weight):
        """Sets the time_weight of this Noise.

        時間重み付け特性   省略時：Slow   - \"slow\"：時定数1sec。   - \"fast\"：時定数0.125sec。   - \"impulse\"：時定数0.035sec。   # noqa: E501

        :param time_weight: The time_weight of this Noise.
        :type time_weight: str
        """
        allowed_values = ["slow", "fast", "impulse"]  # noqa: E501
        if time_weight not in allowed_values:
            raise ValueError(
                "Invalid value for `time_weight` ({0}), must be one of {1}"
                .format(time_weight, allowed_values)
            )

        self._time_weight = time_weight
