patch:
  tags:
    - co2
  summary: '二酸化炭素センサの設定の変更'
  description: |
    指定したフィールドの値を変更する。
    指定されなかったフィールドの値は変更されない。  
    /config/co2.html にブラウザからアクセスすることでも設定変更が可能  
  requestBody:
    description: 省略したパラメータはデフォルト値が適用される
    content:
      application/json:
        schema:
          $ref: "./../components/configCo2.yaml"
  responses:
    200:
      description: '二酸化炭素センサの設定の変更に成功'
      content:
        application/json:
          schema: 
            $ref: "./../components/configCo2.yaml"

get:
  tags:
    - co2
  summary: '二酸化炭素センサの設定の取得'
 
  responses:
    200:
      description: '二酸化炭素センサの設定の取得に成功'
      content:
        application/json:
          schema: 
            $ref: "./../components/configCo2.yaml"