"""
    PoE対応 WebAPI 超音波センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 2.1.x
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mc_uep100_client
from mc_uep100_client.model.network_config_dhcp import NetworkConfigDhcp


class TestNetworkConfigDhcp(unittest.TestCase):
    """NetworkConfigDhcp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkConfigDhcp(self):
        """Test NetworkConfigDhcp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkConfigDhcp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
