"""
    PoE対応 WebAPI 超音波センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 2.0.x
    Generated by: https://openapi-generator.tech
"""


import unittest

import mc_uep100_client
from mc_uep100_client.api.raw_api import RawApi  # noqa: E501


class TestRawApi(unittest.TestCase):
    """RawApi unit test stubs"""

    def setUp(self):
        self.api = RawApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_raw_delete(self):
        """Test case for raw_delete

        生値取得終了  # noqa: E501
        """
        pass

    def test_raw_post(self):
        """Test case for raw_post

        生値取得開始  # noqa: E501
        """
        pass

    def test_raw_status_get(self):
        """Test case for raw_status_get

        生値取得状態の取得  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
