"""
    PoE対応 WebAPI 超音波センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 2.0.x
    Generated by: https://openapi-generator.tech
"""


import unittest

import mc_uep100_client
from mc_uep100_client.api.info_api import InfoApi  # noqa: E501


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self):
        self.api = InfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_info_get(self):
        """Test case for info_get

        機器情報の取得  # noqa: E501
        """
        pass

    def test_info_patch(self):
        """Test case for info_patch

        設定変更が可能な機器情報の変更  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
