"""
    PoE対応 WebAPI 超音波センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 2.0.x
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.rms import Rms


class TestRms(unittest.TestCase):
    """Rms unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRms(self):
        """Test Rms"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Rms()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
