"""
    PoE対応 WebAPI 超音波センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 2.0.x
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mc_uep100_client
from mc_uep100_client.model.sound_level_setting import SoundLevelSetting


class TestSoundLevelSetting(unittest.TestCase):
    """SoundLevelSetting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSoundLevelSetting(self):
        """Test SoundLevelSetting"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SoundLevelSetting()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
