"""
    PoE対応 WebAPI K型熱電対アンプ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 1.2.x
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alert_target_setting import AlertTargetSetting
globals()['AlertTargetSetting'] = AlertTargetSetting
from openapi_client.model.alert_target import AlertTarget


class TestAlertTarget(unittest.TestCase):
    """AlertTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertTarget(self):
        """Test AlertTarget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlertTarget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
