"""
    PoE対応 WebAPI K型熱電対アンプ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 1.2.x
    Generated by: https://openapi-generator.tech
"""


import unittest

import tc_kep100_client
from tc_kep100_client.api.calibration_api import CalibrationApi  # noqa: E501


class TestCalibrationApi(unittest.TestCase):
    """CalibrationApi unit test stubs"""

    def setUp(self):
        self.api = CalibrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_calibration_get(self):
        """Test case for calibration_get

        校正パラメータの取得  # noqa: E501
        """
        pass

    def test_calibration_put(self):
        """Test case for calibration_put

        熱電対の校正を実行  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
