"""
    PoE対応 WebAPI K型熱電対アンプ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 1.2.x
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import tc_kep100_client
from tc_kep100_client.model.network_config_auth import NetworkConfigAuth
from tc_kep100_client.model.network_config_dhcp import NetworkConfigDhcp
globals()['NetworkConfigAuth'] = NetworkConfigAuth
globals()['NetworkConfigDhcp'] = NetworkConfigDhcp
from tc_kep100_client.model.network_config import NetworkConfig


class TestNetworkConfig(unittest.TestCase):
    """NetworkConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkConfig(self):
        """Test NetworkConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
