"""
    PoE対応 WebAPI K型熱電対アンプ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 1.2.x
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.info_api import InfoApi  # noqa: E501


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self):
        self.api = InfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_info_get(self):
        """Test case for info_get

        機器情報の取得  # noqa: E501
        """
        pass

    def test_info_patch(self):
        """Test case for info_patch

        設定変更が可能な機器情報の変更  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
