"""
    PoE対応 WebAPI K型熱電対アンプ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 1.2.x
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import tc_kep100_client
from tc_kep100_client.model.alert_without_ftp import AlertWithoutFTP
globals()['AlertWithoutFTP'] = AlertWithoutFTP
from tc_kep100_client.model.alert_callback import AlertCallback


class TestAlertCallback(unittest.TestCase):
    """AlertCallback unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertCallback(self):
        """Test AlertCallback"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlertCallback()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
