# flake8: noqa

"""
    PoE対応 WebAPI 超音波センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 2.0.x
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from mc-uep100-client.api_client import ApiClient

# import Configuration
from mc-uep100-client.configuration import Configuration

# import exceptions
from mc-uep100-client.exceptions import OpenApiException
from mc-uep100-client.exceptions import ApiAttributeError
from mc-uep100-client.exceptions import ApiTypeError
from mc-uep100-client.exceptions import ApiValueError
from mc-uep100-client.exceptions import ApiKeyError
from mc-uep100-client.exceptions import ApiException
