# flake8: noqa

"""
    PoE対応 WebAPI CO2センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 1.0.x
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from ct_ep100_client.api_client import ApiClient

# import Configuration
from ct_ep100_client.configuration import Configuration

# import exceptions
from ct_ep100_client.exceptions import OpenApiException
from ct_ep100_client.exceptions import ApiAttributeError
from ct_ep100_client.exceptions import ApiTypeError
from ct_ep100_client.exceptions import ApiValueError
from ct_ep100_client.exceptions import ApiKeyError
from ct_ep100_client.exceptions import ApiException
