# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Temperature(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, temperature=None, unit='Celsius'):  # noqa: E501
        """Temperature - a model defined in OpenAPI

        :param temperature: The temperature of this Temperature.  # noqa: E501
        :type temperature: float
        :param unit: The unit of this Temperature.  # noqa: E501
        :type unit: str
        """
        self.openapi_types = {
            'temperature': float,
            'unit': str
        }

        self.attribute_map = {
            'temperature': 'temperature',
            'unit': 'unit'
        }

        self._temperature = temperature
        self._unit = unit

    @classmethod
    def from_dict(cls, dikt) -> 'Temperature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The temperature of this Temperature.  # noqa: E501
        :rtype: Temperature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def temperature(self):
        """Gets the temperature of this Temperature.

        temperature  # noqa: E501

        :return: The temperature of this Temperature.
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this Temperature.

        temperature  # noqa: E501

        :param temperature: The temperature of this Temperature.
        :type temperature: float
        """

        self._temperature = temperature

    @property
    def unit(self):
        """Gets the unit of this Temperature.

        単位  # noqa: E501

        :return: The unit of this Temperature.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this Temperature.

        単位  # noqa: E501

        :param unit: The unit of this Temperature.
        :type unit: str
        """
        allowed_values = ["Kelvin", "Celsius", "Fahrenheit"]  # noqa: E501
        if unit not in allowed_values:
            raise ValueError(
                "Invalid value for `unit` ({0}), must be one of {1}"
                .format(unit, allowed_values)
            )

        self._unit = unit
