# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ThermocoupleCalib(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, unit='Celsius', offset=0):  # noqa: E501
        """ThermocoupleCalib - a model defined in OpenAPI

        :param unit: The unit of this ThermocoupleCalib.  # noqa: E501
        :type unit: str
        :param offset: The offset of this ThermocoupleCalib.  # noqa: E501
        :type offset: float
        """
        self.openapi_types = {
            'unit': str,
            'offset': float
        }

        self.attribute_map = {
            'unit': 'unit',
            'offset': 'offset'
        }

        self._unit = unit
        self._offset = offset

    @classmethod
    def from_dict(cls, dikt) -> 'ThermocoupleCalib':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The thermocoupleCalib of this ThermocoupleCalib.  # noqa: E501
        :rtype: ThermocoupleCalib
        """
        return util.deserialize_model(dikt, cls)

    @property
    def unit(self):
        """Gets the unit of this ThermocoupleCalib.

        単位  # noqa: E501

        :return: The unit of this ThermocoupleCalib.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this ThermocoupleCalib.

        単位  # noqa: E501

        :param unit: The unit of this ThermocoupleCalib.
        :type unit: str
        """
        allowed_values = ["Kelvin", "Celsius", "Fahrenheit"]  # noqa: E501
        if unit not in allowed_values:
            raise ValueError(
                "Invalid value for `unit` ({0}), must be one of {1}"
                .format(unit, allowed_values)
            )

        self._unit = unit

    @property
    def offset(self):
        """Gets the offset of this ThermocoupleCalib.

        温度オフセット値   デフォルト値：0   # noqa: E501

        :return: The offset of this ThermocoupleCalib.
        :rtype: float
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this ThermocoupleCalib.

        温度オフセット値   デフォルト値：0   # noqa: E501

        :param offset: The offset of this ThermocoupleCalib.
        :type offset: float
        """

        self._offset = offset
