"""
    PoE対応 WebAPI CO2センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 1.0.x
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ct_ep100_client
from ct_ep100_client.model.config_co2 import ConfigCo2


class TestConfigCo2(unittest.TestCase):
    """ConfigCo2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigCo2(self):
        """Test ConfigCo2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConfigCo2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
