"""
    PoE対応 WebAPI CO2センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 1.0.x
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ct_ep100_client
from ct_ep100_client.model.alert_target import AlertTarget


class TestAlertTarget(unittest.TestCase):
    """AlertTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertTarget(self):
        """Test AlertTarget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlertTarget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
