"""
    PoE対応 WebAPI CO2センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 1.0.x
    Generated by: https://openapi-generator.tech
"""


import unittest

import ct_ep100_client
from ct_ep100_client.api.alert_api import AlertApi  # noqa: E501


class TestAlertApi(unittest.TestCase):
    """AlertApi unit test stubs"""

    def setUp(self):
        self.api = AlertApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_alerts_alert_id_delete(self):
        """Test case for alerts_alert_id_delete

        指定したidのアラート設定を削除  # noqa: E501
        """
        pass

    def test_get_alert_by_id(self):
        """Test case for get_alert_by_id

        指定したidのアラート設定を取得  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
