"""
    PoE対応 WebAPI CO2センサ API仕様

    \"Try it out\"機能は、API仕様を製品と同一ネットワーク上のローカルPCにダウンロードしブラウザで開くことで利用できます。   # noqa: E501

    The version of the OpenAPI document: 1.0.x
    Generated by: https://openapi-generator.tech
"""


import unittest

import ct_ep100_client
from ct_ep100_client.api.co2_api import Co2Api  # noqa: E501


class TestCo2Api(unittest.TestCase):
    """Co2Api unit test stubs"""

    def setUp(self):
        self.api = Co2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_co2_get(self):
        """Test case for co2_get

        二酸化炭素濃度の取得  # noqa: E501
        """
        pass

    def test_config_co2_get(self):
        """Test case for config_co2_get

        二酸化炭素センサの設定の取得  # noqa: E501
        """
        pass

    def test_config_co2_patch(self):
        """Test case for config_co2_patch

        二酸化炭素センサの設定の変更  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
