type: object
properties:
  customName:
    description: |
      設定可能な名称  
      ユーザが識別を容易にするために利用する。
    type: string
    maxLength: 32
    example: 'sensor_1'
    default: '"customName" is not set'
  
  blinkLed:
    description: |
      Status LED点滅の有無  
      `false`: デフォルト設定。Status LEDはネットワーク状態に対応した動作を行う  
      `true`: Status LEDを点滅させる（点灯時間と消灯時間は同一）  
      本設定は複数のPoE対応WebAPIセンサが設置され製品裏面に記載されたシリアルナンバーを確認できない場合に、どの機器が操作対象であるのかを目視で確認する際に利用する。  
      ※本設定は電源を再起動するとリセットされる。
    type: boolean
    example: false
    default: false
additionalProperties: false